<a href="https://colab.research.google.com/github/88FaHaD/Deep-learning/blob/main/Matrixmultiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Matrix multiplicaton
## tf.matmul(mat1,mat2)
in mechine learning matrix multiplication are the most common tensor operations

In [ ]:
import tensorflow as tf

In [ ]:
matrix1 = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]], dtype=tf.float32)
matrix2 = tf.constant([[9, 8, 7], [6, 5, 4], [3, 2, 1]], dtype=tf.float32)

In [ ]:
result_matrix=tf.matmul(matrix1,matrix2)
result_matrix

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 30.,  24.,  18.],
       [ 84.,  69.,  54.],
       [138., 114.,  90.]], dtype=float32)>

# Matrix multiplication using python operator  @

In [ ]:
matrix1 @ matrix2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 30.,  24.,  18.],
       [ 84.,  69.,  54.],
       [138., 114.,  90.]], dtype=float32)>

# Matrix multiplication  with tensors of different shape

* Two rules

1 Inner dimensions must match.

2 the resulting matrix must have shape of the outer dimension

In [ ]:
x=tf.constant([[1,2],
               [3,4],
               [5,6]])
y=tf.constant([[2,3,4],
               [5,6,7],
               [8,8,20]])

# eror for z = tf.matmul(x,y)
z = tf.matmul(y,x)
z

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 31,  40],
       [ 58,  76],
       [132, 168]], dtype=int32)>

In [ ]:
tf.shape(x)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2], dtype=int32)>

# using tf.reshape

In [ ]:
x=tf.reshape(x,shape=(2,3))

In [ ]:
z=tf.matmul(x,y)
z

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 36,  39,  78],
       [ 81,  90, 171]], dtype=int32)>

In [ ]:
x=tf.constant([[100,200],[300,400]])
y=tf.constant([[1,2,3,4]])
tf.shape(y)


<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 4], dtype=int32)>

In [ ]:
# error if we try to perform tf.matmul(x,y)


In [ ]:
# Now we use reshaping
y=tf.reshape(y,shape=(2,2))
tf.shape(y)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 2], dtype=int32)>

In [ ]:
z=tf.matmul(x,y)
z

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 700, 1000],
       [1500, 2200]], dtype=int32)>

# using tf.transpose
* tf.transpose swaps the axes (dimensions) of a tensor, effectively flipping its rows and columns for 2D tensors. It is commonly used when adjusting tensor dimensions for compatibility in mathematical operations or neural network layers.

## Difference Between tf.transpose and tf.reshape:
tf.transpose rearranges the axes of a tensor without changing its shape (number of elements stays the same).
tf.reshape changes the shape of a tensor while preserving the order of elements and the total number of elements.


In [ ]:
x=tf.constant([[1,2],[3,4],[5,6]])
tf.transpose(x)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3], dtype=int32)>

In [ ]:
y=tf.constant([[1,2],[3,4],[5,6]])


In [ ]:
z=tf.matmul(tf.transpose(x),y)
z

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[35, 44],
       [44, 56]], dtype=int32)>

# The dotproduct
matrix multiplication also refered as dot product.

matrix multiplication can e performed using

* tf.matmul()
* tf.tensordot()

In [ ]:
tf.tensordot(tf.transpose(x),y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[35, 44],
       [44, 56]], dtype=int32)>