<a href="https://colab.research.google.com/github/88FaHaD/Deep-learning/blob/main/Tensorflowfundamentals2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Changing datatypes
a=tf.cast(a,dtype=tf.float16)


In [ ]:
import tensorflow as tf

In [ ]:
a=tf.constant([[3,5],[4,5]],tf.float32)
a.dtype

tf.float32

# Reduced precision
Precision refers to how accurate a number is when stored or calculated. Higher precision means more accuracy, and lower precision means less accuracy. higher precision means more memory is needed.

Reduced Precision uses fewer bits to store numbers, making calculations faster and using less memory but with a slight loss in accuracy.

In [ ]:
a=tf.cast(a,dtype=tf.float16)
a

<tf.Tensor: shape=(2, 2), dtype=float16, numpy=
array([[3., 5.],
       [4., 5.]], dtype=float16)>

In [ ]:
b=tf.constant([[3,5],[4,5]],tf.float32)
b=tf.cast(b,dtype=tf.int8)
b

<tf.Tensor: shape=(2, 2), dtype=int8, numpy=
array([[3, 5],
       [4, 5]], dtype=int8)>

# Agregating tensors
condensing tensors from multiple values to smaller amount of values
tf.abs take the negative values and get

1.   tf.abs take the negative values and get the postive values
2.   tf.reduce_min(t) gives the minimum value of a tensor
3.   tf.reduce_max(t) gives the maximum value of tensor
4.   tf.reduce_mean(t) gives the mean value of tensor
5.   tf.reduce_sum(t) sum of tensor
6.   tf.math.reduce_variance(t) gives the variance how spread out values are from mean
7.   tf.math.reduce_std(t) gives standard deviation is the square root of the variance, providing a measure of the average distance of the data points from the mean.









In [ ]:
#get the absolute values
f=tf.constant([-10,-20,-30])
f=tf.abs(f)
f

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([10, 20, 30], dtype=int32)>

In [ ]:
# geting the minimum value
f=tf.constant([1,2,3,4,-2,5,8])
min_val=tf.reduce_min(f)
min_val

<tf.Tensor: shape=(), dtype=int32, numpy=-2>

In [ ]:
# geting the maximum value
max_val=tf.reduce_max(f)
max_val

<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [ ]:
# geting the mean
mean_val=tf.reduce_mean(f)
mean_val

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
# sum of tensor
sum_val=tf.reduce_sum(f);
sum_val



<tf.Tensor: shape=(), dtype=int32, numpy=21>

In [ ]:
# variance requires floating point numbers
z=tf.cast(f,dtype=tf.float32)
var_val=tf.math.reduce_variance(z)
var_val


<tf.Tensor: shape=(), dtype=float32, numpy=8.571428>

In [ ]:
# standard deviation
std_val=tf.math.reduce_std(z)
std_val

<tf.Tensor: shape=(), dtype=float32, numpy=2.9277003>

# finding positional maximum and minimum

used when neural network prediction output is given and we want to find the positional maximum and minimum in these outputs

In [18]:
tf.random.set_seed(42)
t=tf.random.uniform(shape=[50])
t

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

# Positional maximum is found using
tf.argmax() gives the position where the maximum value is

In [21]:
tf.argmax(t)


<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [23]:
# get the vhighest value
t[tf.argmax(t)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [24]:
tf.reduce_max(t)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [26]:
# checking if the max values are equal
t[tf.argmax(t)]==tf.reduce_max(t)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

# Positional Minimum
tf.argmin(t)

In [27]:
tf.argmin(t)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [28]:
#printing the value
t[tf.argmin(t)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [29]:
tf.reduce_min(t)

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [33]:
#checking if minimum value are equal
t[tf.argmin(t)]==tf.reduce_min(t)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

# Squeezing a tensor(removing all single dimensions)
s_squeezed=tf.squeeze(s)

In [35]:
tf.random.set_seed(42)
s=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
s

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [36]:
s.shape

TensorShape([1, 1, 1, 1, 50])

In [41]:
s_squeeze=tf.squeeze(s)
s_squeeze
print(s_squeeze)
print()
s_squeeze.shape

tf.Tensor(
[0.6645621  0.44100678 0.3528825  0.46448255 0.03366041 0.68467236
 0.74011743 0.8724445  0.22632635 0.22319686 0.3103881  0.7223358
 0.13318717 0.5480639  0.5746088  0.8996835  0.00946367 0.5212307
 0.6345445  0.1993283  0.72942245 0.54583454 0.10756552 0.6767061
 0.6602763  0.33695042 0.60141766 0.21062577 0.8527372  0.44062173
 0.9485276  0.23752594 0.81179297 0.5263394  0.494308   0.21612847
 0.8457197  0.8718841  0.3083862  0.6868038  0.23764038 0.7817228
 0.9671384  0.06870162 0.79873943 0.66028714 0.5871513  0.16461694
 0.7381023  0.32054043], shape=(50,), dtype=float32)



TensorShape([50])

# One hot encoding
one hot encoding is used for  numerical encoding for the input data
* t_one_hot= tf.one_hot(data,depth)

we can also use custom vlaues for one hot encoding



*   depth defines the number of positions in the one-hot vector.
*  If depth is smaller than the largest number in some_list, it will result in an error.
*  If depth is larger than the largest number, extra zeros will be added to the vectors.



In [53]:
somelist=[0,1,2,3]
tf.one_hot(somelist,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

# Few more math operations
square,log,square root

1.   tf.square(t)
2.   tf.math.sqrt(t but in float)
3.   tf.math.log(t but in float)





In [54]:
# square
sq=tf.range(1,10)
tf.square(sq)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [56]:
# square root
sqrt=tf.range(1,10)
tf.math.sqrt(tf.cast(sqrt,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [58]:
#log
lg=tf.range(1,10)
tf.math.log(tf.cast(lg,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

# tensors and numpy
**Note** One of the main difference between numpy and tensors is that tensor run faster on gpu or tpu for faster numerical processing

In [61]:
# creating a tensor from numpy array
import numpy as np
np=np.array([3.,4.,7.,10.])
t_np=tf.constant(np)
t_np

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([ 3.,  4.,  7., 10.])>

In [69]:
#convert tensor to numpy
t_np_numpy = t_np.numpy()
t_np_numpy

array([ 3.,  4.,  7., 10.])

In [73]:
t_np.dtype,t_np_numpy.dtype

(tf.float64, dtype('float64'))