<a href="https://colab.research.google.com/github/88FaHaD/Deep-learning/blob/main/tf_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)


2.17.1


In [ ]:
import sys
print(sys.version)


3.10.12 (main, Nov  6 2024, 20:22:13) [GCC 11.4.0]


## TF.constant
tf.constant()
creates a constant tensor.
The first argument is the value (e.g., a list or scalar).
dtype specifies the data type of the tensor (optional).

In [ ]:
# creating tensors with tf.constant
scaler=tf.constant(7)
print(scaler)

tf.Tensor(7, shape=(), dtype=int32)


# NDIM IS Used to check the dimension

In [ ]:
scaler.ndim

0

# Creating a vector using tf.comnstant

In [ ]:
vector=tf.constant([7,9])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 9], dtype=int32)>

In [ ]:
vector.ndim

1

# creating a matrix ie more then one dimension

In [ ]:
matrix=tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

# creating a matrix and also giving it data type

In [ ]:
matrix2=tf.constant([[11,11],[12,21],[32,32]],dtype=tf.float16)
matrix2

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[11., 11.],
       [12., 21.],
       [32., 32.]], dtype=float16)>

In [ ]:
matrix2.ndim

2

# creatinng a tensor

In [ ]:
tennsor=tf.constant([[[1,2,3],
                      [3,2,1],
                      [4,5,9]]])
tennsor

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [3, 2, 1],
        [4, 5, 9]]], dtype=int32)>

In [ ]:
tennsor.ndim

3

# Differences
* Scaler is a single number
* vector is a number with direction
* matrix is a 2dimensional array of numbers
* tensor is a n (0-infinity) dimension array of numbers



# Creating tensors with tf.variable
We cannot use .ndim with a tf.Variable object, as it does not have that attribute. Instead, use .shape or tf.rank() to get the dimensional information.

In [ ]:
scaler=tf.Variable(20);
scaler

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=20>

#Changeb:le vs unchangeble tensors


In [ ]:
changeble_tensor=tf.Variable(10,11);
unchangeble=tf.constant(22,11)
print(changeble_tensor,unchangeble)


<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10> tf.Tensor(22, shape=(), dtype=qint8)


#tf.assign
you cannot modify a tf.Variable like a list (using indexing) directly; tf.Variable objects require methods like .assign() to update values.

You cannot modify a tf.constant after it is created because constants are immutable in TensorFlow. Attempting to modify a tf.constant will result in an error

In [ ]:
changeble_tensor.assign(1,9)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=1>

In [ ]:
changeble_tensor

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>

# Creating random tensors
* Random Uniform Tensor: Generates random values from a uniform distribution between minval and maxval.
** tf.random.uniform(shape, minval, maxval)
* Random Normal Tensor: Generates random values from a normal distribution with specified mean and stddev.
** tf.random.normal(shape, mean, stddev)
* Random Integer Tensor: Generates random integer values between minval and maxval.
** tf.random.uniform(shape, minval, maxval, dtype=tf.int32)
* Random Binary Tensor: Generates random values of 0 or 1 (binary) within a specified range.
** tf.random.uniform(shape, minval, maxval, dtype=tf.int32)

# normal vs uniform
* Normal Distribution: Generates values with a bell-shaped curve, where most values are clustered around the mean, and values farther from the mean are less likely.
* Uniform Distribution: Generates values evenly spread within a specified range, where every value has an equal probability of being selected.

In [ ]:
random_values1 = tf.random.uniform(shape=(5, 5), minval=0, maxval=10)
random_values2=tf.random.normal(shape=(2,2),mean=0,stddev=10)
random3=tf.random.uniform(shape=(3,3),minval=9,maxval=50,dtype=tf.int32)
random4=tf.random.uniform(shape=(3,3),minval=0,maxval=2,dtype=tf.int32)

In [ ]:
print(random_values1)

tf.Tensor(
[[9.237441   4.3168855  4.3494043  5.2788615  9.518768  ]
 [0.03773689 3.2934177  8.336596   9.2007675  8.907809  ]
 [2.9921603  6.041434   8.202704   6.6910005  2.9892826 ]
 [8.629838   0.9334433  5.3337803  4.9628854  6.992669  ]
 [2.9307961  4.7181406  6.135708   9.763932   0.8141303 ]], shape=(5, 5), dtype=float32)


In [ ]:
print(random_values2)

tf.Tensor(
[[ -4.352831   11.108933 ]
 [ -3.8422446 -13.65526  ]], shape=(2, 2), dtype=float32)


In [ ]:
print(random3)

tf.Tensor(
[[19 11 34]
 [38 44 12]
 [34 38 13]], shape=(3, 3), dtype=int32)


In [ ]:
print(random4)

tf.Tensor(
[[0 0 0]
 [0 0 1]
 [1 1 1]], shape=(3, 3), dtype=int32)


# tf.random.Generator.from.seed()
* Definition: tf.random.Generator.from_seed() initializes a TensorFlow RNG with a specified seed value.
* Why Use: It ensures reproducibility of random numbers, making experiments consistent across multiple runs.
* When to Use: Use it when you need deterministic random behavior for debugging, research, or when random operations must be replicated exactly.

In [ ]:
import tensorflow as tf

# Create a random generator with a seed
rng = tf.random.Generator.from_seed(42)

# Generate random integers between minval (-1) and maxval (4)
random_integers = rng.uniform(shape=(2, 2), minval=1, maxval=4, dtype=tf.int32)

print("Random Integers:")
print(random_integers)


Random Integers:
tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)


# Shuffling elements of tensors
reason is that if some type of data is contnuous i would impact the over all prediction of our model so inorder to solve it we need to schufle our tensors


In [ ]:
not_shufle=tf.constant([[10,7],[9,10],[11,10]])
not_shufle.ndim

2

# tf.random.shuffle(name of tensor)

In [ ]:
shufled_tensor=tf.random.shuffle(not_shufle)

In [ ]:
print("non shuffle tensor ",not_shufle)

non shuffle tensor  tf.Tensor(
[[10  7]
 [ 9 10]
 [11 10]], shape=(3, 2), dtype=int32)


In [ ]:
print("shuffled tensor ",shufled_tensor)

shuffled tensor  tf.Tensor(
[[ 9 10]
 [10  7]
 [11 10]], shape=(3, 2), dtype=int32)


# TENSORFLOW OPERATION SIMLAR TO NUMPY


In [ ]:
tf.ones([7,7])

<tf.Tensor: shape=(7, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros([8,4])

<tf.Tensor: shape=(8, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turnning numpy arrays into tensors
The main difference between numpy arrays and tenosrflow tensors is that tensors run faster on gpu

In [ ]:
import numpy as np

In [ ]:
numpy_a=np.arange(0,30,dtype=np.int32)
numpy_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29], dtype=int32)

In [ ]:
a=tf.constant(numpy_a,shape=(6,5)) # make sure the nsize is equal to number of elements in our case 30 elements so 6*5 or %*6 or 3*2 *5
a

<tf.Tensor: shape=(6, 5), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]], dtype=int32)>

### Geting information from tensors

* Shape tensor.shape :-> number of elements of each dimension of tensor
* Rank tf.rank(tensor) :-> number of tensor dimensions.
* axis or dimension tensor[0].numpy(),tensor[:,1] :-> a perticular dimesnion of tensor
* size tf.size(tensor) :-> number of elements in tensor


In [ ]:
t1=tf.Variable([[2,4],[7,9],[20,20]])

In [ ]:
print("Shape of tensor is ",t1.shape)
print("Rank of tensor",tf.rank(t1))
print("first row ", t1[0].numpy())

Shape of tensor is  (3, 2)
Rank of tensor tf.Tensor(2, shape=(), dtype=int32)
asis 0 and axis 1,1 is [2 4]


In [ ]:
print("second row ",t1[1].numpy())

second row  [7 9]


In [ ]:
print("first element ",t1[0,0].numpy())
print("last element ",t1[2,1].numpy())

first element  2
last element  20


In [ ]:
print("size of tensor is ",tf.size(1))

size of tensor is  tf.Tensor(1, shape=(), dtype=int32)


# Issue with tf.size on tf.varaible
* The issue you're seeing, where tf.size(t1) prints 1, is because t1 is a tf.Variable and tf.size behaves differently when applied directly to a tf.Variable in some contexts.

* To correctly obtain the number of elements in a tf.Variable, you should first convert it into a TensorFlow tensor (if necessary) and then compute the size using tf.size().

In [ ]:
size=tf.size(t1) # tf.size(t1).numpy()
print("size of tensor is ",size.numpy())

size of tensor is  6


In [ ]:
print("datatype is ",t1.dtype)

datatype is  <dtype: 'int32'>


# Indexing tensors NUMPY WAY
* tensors can be indexed just like python lists


In [ ]:
# getting first two elements of each dimension
t2=tf.Variable([[2,2,4],[3,3,4],[8,0,9]])
print("first two elemets of first dimenson are as ",t2[0,0].numpy(),t2[0,1].numpy())
print("first two elemets of second dimenson are as ",t2[1,0].numpy(),t2[1,1].numpy())
print("first two elemets of third dimenson are as ",t2[2,0].numpy(),t2[2,1].numpy())

first two elemets of first dimenson are as  2 2
first two elemets of second dimenson are as  3 3
first two elemets of third dimenson are as  8 0


# TENSOR WAY

In [ ]:
print(t2[:2,:2])

tf.Tensor(
[[2 2]
 [3 3]], shape=(2, 2), dtype=int32)


In [ ]:
# get the first element from each dimension from each index except for the final one
print(t2[:2:2])


tf.Tensor([[2]], shape=(1, 1), dtype=int32)


In [ ]:
# geting the last element of each dimension from tensor
t3=tf.constant([[2,2],[3,4]])
print("last element of each dimenson of tensor are as ",t3[:,:-1])


last element of each dimenson of tensor are as  tf.Tensor(
[[2]
 [3]], shape=(2, 1), dtype=int32)


# Expanding of tensors

In [ ]:
t4=tf.Variable([[8,8],[9,9]])
t4=t3[...,tf.newaxis]
print(t4)

tf.Tensor(
[[[2]
  [2]]

 [[3]
  [4]]], shape=(2, 2, 1), dtype=int32)


# Alternative way


In [ ]:
tf.expand_dims(t4,axis=-1)# in the end extra dimension

<tf.Tensor: shape=(2, 2, 1, 1), dtype=int32, numpy=
array([[[[2]],

        [[2]]],


       [[[3]],

        [[4]]]], dtype=int32)>

In [ ]:
tf.expand_dims(t4,axis=0) # in the in the start

<tf.Tensor: shape=(1, 2, 2, 1), dtype=int32, numpy=
array([[[[2],
         [2]],

        [[3],
         [4]]]], dtype=int32)>

In [ ]:
tf.expand_dims(t4,axis=1) # in the middle

<tf.Tensor: shape=(2, 1, 2, 1), dtype=int32, numpy=
array([[[[2],
         [2]]],


       [[[3],
         [4]]]], dtype=int32)>

#Manipulation of Tensors

## Basic operation

*  +, -, /, *

In [ ]:
# addition
tensor =tf.constant([[10,7],[3,4]])
tensor = tensor+10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# subtraction
tensor=tensor-10
tensor


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Multiplication
tensor =tensor*10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# division
tensor =tensor/10
tensor

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[10.,  7.],
       [ 3.,  4.]])>

# using pre built functions or basic operations

In [ ]:
tensor2=tf.constant([[2,4],[9,18]])
tensor2=tf.multiply(tensor2,10)
tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 20,  40],
       [ 90, 180]], dtype=int32)>

In [ ]:
tensor2=tf.add(tensor2,20)
tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 40,  60],
       [110, 200]], dtype=int32)>

In [ ]:
tensor2=tf.subtract(tensor2,10)
tensor2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 30,  50],
       [100, 190]], dtype=int32)>

In [ ]:
tensor2=tf.divide(tensor2,10)
tensor2

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[ 3.,  5.],
       [10., 19.]])>